# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [7]:
# list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉
# tolist() 才可達成多層的型態轉換

'list(a)'的轉換結果會是視為每一層的array為基礎元素進行轉換
'a.tolist()'的轉換結果才會是將每一個元素進行型態轉換


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [39]:
import numpy as np
a = np.random.randint(10, size=6) 

print(a)
print('ndim: ', a.ndim) #陣列的維度數目
print('shape: ', a.shape) #陣列形狀
print('size: ', a.size) #陣列元素總數
print('dtype: ', a.dtype) #陣列元素資料型別
print('itemsize: ', a.itemsize) #陣列中每個元素佔用的空間
print('len:',len(a)) #有多少個陣列
print('type:',type(a)) #資料型別

[7 9 1 8 2 8]
ndim:  1
shape:  (6,)
size:  6
dtype:  int32
itemsize:  4
len: 6
type: <class 'numpy.ndarray'>


In [24]:
import numpy as np
b = np.random.randint(10, size=(3,4)) 

print(b)
print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('len:',len(b))
print('type:',type(b))

[[8 4 8 2]
 [2 9 2 9]
 [8 6 7 0]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int32
itemsize:  4
len: 3
type: <class 'numpy.ndarray'>


In [25]:
import numpy as np
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('len:',len(c))
print('type:',type(c))

[[[3 0]
  [4 3]
  [4 1]]

 [[2 0]
  [8 5]
  [5 6]]]
ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int32
itemsize:  4
len: 2
type: <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [38]:
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

def tolist(data):
    result = []
    if data.ndim == 1:
        return list(data)
    else:
        for i in data:
            result.append(tolist(i))
    return result

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 8, 1, 7, 5, 2]
[[5, 5, 6, 1], [9, 2, 2, 9], [3, 4, 8, 1]]
[[[4, 9], [4, 0], [1, 1]], [[6, 0], [8, 4], [3, 3]]]
