# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
#np.zero()產生的是元素全為 0 的陣列
#np.empty()產生的是元素都極接近 0 的陣列

'\nYour Code\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [7]:
import numpy as np

In [8]:
# 參考解答

a = np.random.rand(2, 3)
a = a*10
print('原本的陣列:\n',a)

#直接去掉小數
b = np.floor(a)
print('去掉小數後:\n',b)

#四捨五入
c = np.round(a)
print('四捨五入後:\n',c)

原本的陣列:
 [[7.37347975 1.01347389 7.72435556]
 [1.15147529 7.36313483 2.18605334]]
去掉小數後:
 [[7. 1. 7.]
 [1. 7. 2.]]
四捨五入後:
 [[7. 1. 8.]
 [1. 7. 2.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [14]:
#不使用整數亂數法
m = 20
n = 40

a = np.random.rand(2, 3)
a = a*(n-m)+m
a = np.floor(a)
print(a)

[[36. 31. 21.]
 [36. 25. 22.]]


In [16]:
#使用整數亂數法
from numpy.random import default_rng
rng = default_rng()
m = 20
n = 40
a = rng.integers(m, n, size=(2, 3))
print(a)

[[21 20 33]
 [24 27 36]]
