# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
import numpy as np

In [30]:
a = np.arange(1,12)
print(a)
a[3:7] *= -1
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3 -4 -5 -6 -7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [42]:
A = np.random.rand(3, 6)

res = A[A>0.5]
print(A)
print(res)
print(res.size)

[[0.77777683 0.22448926 0.86406323 0.34562802 0.9430829  0.65985701]
 [0.58096358 0.25524586 0.41690223 0.55399719 0.70266194 0.15186102]
 [0.7985445  0.87915636 0.72141749 0.48989519 0.12875434 0.03212356]]
[0.77777683 0.86406323 0.9430829  0.65985701 0.58096358 0.55399719
 0.70266194 0.7985445  0.87915636 0.72141749]
10
