# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
#a.sum() 及 np.sum(a) 是 numpy 所提供的函式，一個是以array為基礎，另一個是numpy為基礎
#sum(a) 是 python本身的函式

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [ ]:
# 標準化(Standization)：將資料以特定的加減乘除使其尺度落於一樣的0-1，可以使各資料的權重差不多。
# 規一化(Normalization)：將資料除去單位，並使其數值領域維0-1，可以讓不同屬性的資料可以比較
# 公式 = Xnom = (X - Xmin) / (Xmax - Xmin)

In [1]:
import numpy as np
A = np.random.random((5, 5))

A = (A - A.min())/(A.max() - A.min())
print(A)

[[0.50720573 0.2846315  0.78146555 1.         0.55180147]
 [0.92414145 0.05749023 0.14176487 0.         0.69614186]
 [0.6735688  0.66399078 0.98957943 0.64565119 0.94784666]
 [0.50722498 0.64430506 0.13953564 0.63719172 0.93744872]
 [0.59099041 0.26468872 0.98287822 0.26369191 0.44593653]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [15]:
import numpy as np
B = np.random.randint(0,100,10)
print(B)
print('最大值是: ',max(B))
B[B.argmax()] = -1
print(B)

[19 94 83 12 25 17 14 61 73 43]
最大值是:  94
[19 -1 83 12 25 17 14 61 73 43]
